default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV["DB_NAME"] || Rails.application.credentials[:production][:db_name] %>
  host: <%= ENV["DB_HOST"] || Rails.application.credentials[:production][:db_host] %>
  username: <%= ENV["DB_USERNAME"] || Rails.application.credentials[:production][:db_username] %>
  password: <%= ENV["DB_PASSWORD"] || Rails.application.credentials[:production][:db_password] %>
